oxia-db/oxia

- README.md
Resize the logo to 300:300 and place it on the right.
The preview over there:
> Resize the logo

- deploy/dashboards/oxia-containers.json
- deploy/dashboards/oxia-coordinator.json
- deploy/dashboards/oxia-golang.json
- deploy/dashboards/oxia-grpc.json
- deploy/dashboards/oxia-nodes.json
- deploy/dashboards/oxia-overview.json
- deploy/dashboards/oxia-shards.json
Fixed metrics labels in dashboards: 
* `job` -> `app_kubernetes_io_component`
* `pod` -> `kubernetes_pod_name`
> Fixed dashboards to use `kubernetes_pod_name` labels

- cmd/main.go
- cmd/pebble/cmd.go
- server/kv/kv_pebble.go
The tools allows for debug / inspect / repair a Pebble DB.
> Added Pebble DB CLI util tool

- server/leader_controller.go
Fixed: https://github.com/streamnative/oxia/issues/324
> fix(324): close channel after iterator is closed

- coordinator/impl/coordinator_e2e_test.go
Use Steady status cause flaky test
> test(*): flaky TestCoordinator_RebalanceCluster

- .golangci.yaml
- server/kv/db.go
- server/quorum_ack_tracker.go
- server/quorum_ack_tracker_test.go
> chore(*): enable nilnil linter

- .golangci.yaml
- cmd/client/cmd_test.go
- common/condition_test.go
- common/wait_group_test.go
- coordinator/impl/coordinator_e2e_test.go
- coordinator/impl/metadata_test.go
- coordinator/impl/mock_test.go
- oxia/async_client_impl_test.go
- oxia/cache_test.go
- oxia/internal/metrics/metrics_test.go
- oxia/internal/shard_manager_test.go
- oxia/sync_client_impl_test.go
- server/follower_controller_test.go
- server/kv/notifications_trimmer_test.go
- server/leader_controller_test.go
- server/session_manager_test.go
- server/standalone.go
- server/wal/wal_test.go
> chore(*): enable thelper linter

- .golangci.yaml
- oxia/example_test.go
enable `testableexamples` linter
> chore(*): enable testableexamples linter

- .golangci.yaml
- cmd/main.go
- common/container/container.go
- common/metrics/metrics.go
- common/pprof.go
- coordinator/impl/coordinator.go
- coordinator/impl/node_controller.go
- coordinator/impl/shard_controller.go
- oxia/cache.go
- oxia/cache_test.go
- oxia/internal/shard_manager.go
- oxia/notifications.go
- oxia/sessions.go
- perf/perf.go
- server/follower_controller.go
- server/follower_cursor.go
- server/kv/notifications_trimmer.go
- server/leader_controller.go
- server/util/stream_reader.go
- server/wal/wal_impl.go
- server/wal/wal_trimmer.go
enable linters：
- contextcheck
- noctx
- gomoddirectives
> chore(*): enable contextcheck、noctx、gomoddirectives linter

- .golangci.yaml
- common/memoize.go
- coordinator/impl/shard_controller.go
- maelstrom/dispatcher.go
- maelstrom/grpc_provider.go
- oxia/cache.go
- oxia/sync_client_impl.go
- server/follower_controller.go
- server/kv/db.go
- server/kv/kv_pebble.go
- server/wal/wal_impl.go
> chore(*): enable gocritic linter

- docs/k8s-deploy.md
tag: main
image: streamnative/oxia
> improve deploy doc

- server/quorum_ack_tracker.go
The new async quorum-ack-tracker, added to support write-stream requests, should trigger callback outside of a mutex to avoid a deadlock situation at closing time.
```
1 @ 0x10217de88 0x102110e90 0x102110ac8 0x103714d40 0x103719c00 0x103714bf8 0x103714a58 0x103715378 0x1036e7c8c 0x102725c54 0x102716428 0x102725bbc 0x1021869f4
#	0x103714d3f	github.com/streamnative/oxia/server.(*leaderController).handleWalSynced.func2+0x8f		/Users/mmerli/prg/oxia/server/leader_controller.go:913
#	0x103719bff	github.com/streamnative/oxia/server.(*quorumAckTracker).WaitForCommitOffsetAsync+0x10f		/Users/mmerli/prg/oxia/server/quorum_ack_tracker.go:206
#	0x103714bf7	github.com/streamnative/oxia/server.(*leaderController).handleWalSynced+0x167			/Users/mmerli/prg/oxia/server/leader_controller.go:902
# …
```
> Async quorum-ack-tracker should trigger callback outside of mutex

- server/kv/db.go
return storage entry to vtpool when callback error
> feat(server): return storage entry to vtpool when callback error

- coordinator/coordinator.go
- coordinator/coordinator_test.go
Fix coordinator config marshalling error.
- filter unsupported json type
> fix(coordinator): fix config marshaling error

- server/internal_rpc_server.go
use the correct error for the log.
> fix(server): use the correct err for internal server log

- common/client_pool.go
- common/client_pool_test.go
Same as https://github.com/streamnative/oxia-java/pull/192.  Support auto-enable TLS on the client.
> feat(client): support auto enable tls by schema

- .github/workflows/pr_build_and_test.yaml
- common/collection/map.go
- common/collection/visible_map.go
- common/collection/visible_map_test.go
- server/session.go
- server/session_manager.go
Fixed the deadlock caused by the metrics register lock. 
FYI: [block.log](https://github.com/user-attachments/files/18522124/block.log)
> fix: fix the deadlock caused by metrics gauge callback

- server/session.go
- server/session_manager.go
> nightly: fix deadlock caused by session close/delete

- .github/workflows/pr_build_and_test.yaml
Fix：https://github.com/streamnative/oxia/issues/612
> fix(612): validate git status if clean after lint

- server/wal/wal_ro_segment.go
- server/wal/wal_ro_segment_test.go
Fix: https://github.com/streamnative/oxia/issues/594
> fix(594): ignore txnFile not exists when trim segments

- coordinator/impl/coordinator.go
- coordinator/impl/coordinator_e2e_test.go
- coordinator/impl/shard_controller.go
Fix: https://github.com/streamnative/oxia/issues/620
> fix(620): wait shard controller loop exit when close it

- server/wal/wal.go
- server/wal/wal_impl.go
- server/wal/wal_rw_segment.go
- server/wal/wal_rw_segment_test.go
- server/wal/wal_trimmer_test.go
Fix: https://github.com/streamnative/oxia/issues/619
> fix(619): append into ReadWriteSegment when it exceeded size should not panic

- server/session_manager.go
Fix the session manager deadlock.  
[goroutine.txt](https://github.com/user-attachments/files/19716457/goroutine.txt)
```
1 @ 0x4773ce 0x453e85 0x453e54 0x478945 0x48c77d 0x48daf1 0x48dad2 0x1bb593a 0x1bb569b 0x1bc23a5 0x1bc2118 0x1bb8522 0x1bbbc9a 0x9e2b8b 0x9c49dd 0x9e29e3 0x9afaeb 0x9b4aab 0x9ad7ff 0x47f681
#	0x478944	sync.runtime_SemacquireMutex+0x24									/usr/local/go/src/runtime/sema.go:95
#	0x48c77c	sync.(*Mutex).lockSlow+0x15c										/usr/local/go/src/sync/mutex.go:173
#	0x48daf0	sync.(*Mutex).Lock+0x30											/usr/local/go/src/sync/mutex.go:92
#	0x48dad1	sync.(*RWMutex).Lock+0x11										/usr/local/go/src/sync/rwmutex.go:148
#	0x1bb5939	github.com/streamnative/oxia/server.(*leaderController).appendToWal+0x79				/src/oxia/server/leader_controller.go:809
#	0x1bb569a …
```
> fix: fix session manager deadlock

- coordinator/impl/shard_controller.go
Fix the wrong metric collection.
- use the correct `becomeLeaderLatency`
> fix(coordinator): fix wrong metric collection

- docs/go-api.md
Include all the features that were missing from the original documentation. The updated documentation now includes:
1. Client Options - A comprehensive section on all available client options with their descriptions and default values
2. Authentication - Documentation on token-based authentication with examples
3. Conditional Operations - Examples of how to use conditional operations with expected version IDs
4. Partition Keys - Explanation and examples of using partition keys for co-locating records
5. Sequential Keys - Documentation on creating records with server-assigned sequential keys
6. Secondary Indexes - Examples of creating and using secondary indexes
7. Key Comparison Operations - Documentation on the various key comparison operations for Get requests
8. Range Operations - …
> Update Go client API documentation with new features

- coordinator/impl/coordinator_e2e_test.go
- server/leader_controller.go
Fix the flaky test TestCoordinator_ShrinkCluster.
> fix: fix the flaky test TestCoordinator_ShrinkCluster

- server/leader_controller.go
Complete error when the context is done to make the logic clearer.
> fix: complete err when context done

- server/kv/db_sequences_wait_tracker.go
- server/kv/db_sequences_wait_tracker_test.go
> fix: make sequenceWaiter close Idempotent

- go.mod
- go.sum
Upgraded dependencies go-viper to fix the issue https://github.com/oxia-db/oxia/security/code-scanning/15
> fixes: fix GHSA-fv92-fjc5-jj9h

- server/public_rpc_server.go
Fixes: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10455fcd0]
goroutine 83 [running]:
github.com/oxia-db/oxia/server.(*publicRpcServer).Write(0x1400031b040, {0x1050bfda8, 0x140005936e0}, 0x1400057c700)
/Users/mmerli/prg/oxia/server/public_rpc_server.go:105 +0x120
github.com/oxia-db/oxia/proto._OxiaClient_Write_Handler.func1({0x1050bfda8?, 0x140005936e0?}, {0x104fcd0c0?, 0x1400057c700?})
/Users/mmerli/prg/oxia/proto/client_grpc.pb.go:491 +0xd0
github.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3({0x1050bfda8, 0x140005936e0}, {0x104fcd0c0, 0x1400057c700}, 0x80?, 0x14000513578)
/Users/mmerli/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/se …
```
> Always validate shard id not to be null
