oxia-db/oxia

common/container/container.go
deploy/charts/oxia-cluster/templates/_helpers.tpl
deploy/charts/oxia-cluster/templates/server-statefulset.yaml
server/assignment_dispatcher.go
server/assignment_dispatcher_test.go
server/internal_rpc_server.go
server/internal_rpc_server_test.go
server/server.go

The oxia server should not considered to be "ready" to be put in the load-balancer rotation for service discovery until it has received the shards mapping from the coordinator. This can happen 10s of seconds after restarting a storage pod.
Added gRPC service `oxia-readiness` that can be probed from K8S readiness probe, so that we don't get a client to ask for service discovery to a pod that does not have that information yet.

Added readiness support in server health-check

---

server/follower_controller.go
server/follower_controller_test.go

When a send snapshot fails (eg: wrong term sent by the leader), the follower is left with the database closed and subsequent `NewTerm()` request is causing a panic for `nil` pointer.
```
{"level":"warn","component":"follower-controller","namespace":"matteo","shard":5,"term":9,"error":"rpc error: code = Code(101) desc = oxia: invalid term","time":"2023-06-10T19:13:06.66252744Z","message":"Error in handle Replicate stream"}
{"level":"warn","component":"internal-rpc-server","error":"rpc error: code = Code(101) desc = oxia: invalid term","namespace":"matteo","shard":5,"peer":"10.48.4.251:50338","time":"2023-06-10T19:13:06.662638529Z","message":"SendSnapshot failed"}
{"level":"info","component":"internal-rpc-server","req":{"namespace":"matteo","shardId":"5","term":"10"},"peer":"10.48.5.53:58010 …
```

Fixed reopening of db in follower after a failed snapshot request

---

common/metrics/counter.go
server/shards_director.go

When there is a leader election and a Prometheus metrics collection event is happening there is potential for a deadlock between these 2 go-routines:
This holds the metrics registry mutex and acquires the read-only mutex on the shards director
```
1 @ 0x4481f6 0x4594fe 0x4594d5 0x475965 0x1a67dfb 0x1a67dd7 0xa56d5e 0xa35aa6 0xa38667 0xa3198e 0xa51a82 0x8a3253 0x479a01
#	0x475964	sync.runtime_SemacquireMutex+0x24						/usr/local/go/src/runtime/sema.go:77
#	0x1a67dfa	sync.(*RWMutex).RLock+0x5a							/usr/local/go/src/sync/rwmutex.go:71
#	0x1a67dd6	oxia/server.NewShardsDirector.func1+0x36					/src/oxia/server/shards_director.go:71
#	0xa56d5d	oxia/common/metrics.NewGauge.func1+0x5d						/src/oxia/common/metrics/gauge.go:58
#	0xa35aa5 …
```

Fixed metrics gauge callback deadlock

---

deploy/charts/oxia-cluster/templates/coordinator-configmap.yaml
deploy/charts/oxia-cluster/templates/server-service-public.yaml
deploy/charts/oxia-cluster/templates/server-statefulset.yaml

Oxia servers right now use the K8S Service for 2 different purposes: 
1. Expose a single URL for an Oxia cluster service discovery
2. Provide DNS names for individual pods, so that either other oxia pods can contact or clients can connect directly.
for (1) we want that only the pods that are "ready" (meaning they have the current shards mapping) are exposed in the service rotation.
for (2), we need the pods to have a DNS name available immediately when they start, so that the Oxia coordinator can connect to them (through their DNS name), send the shards mapping and make them "ready". For this we can use the K8S `publishNotReadyAddresses: true` property on the service configuration.
The 2 goals are in contrast between each others and there seems to be no way to achieve both of them with a …

Use `-svc` internal service for readiness

---

server/leader_controller.go

At collection time, we have the Otel lock and try to grab the leader controller read-lock
```
1 @ 0x4482d6 0x4595de 0x4595b5 0x475a45 0x1a6d77b 0x1a6d757 0xa50f9e 0xa2f726 0xa322e7 0xa2b60e 0xa4b702 0x89c9d3 0x479ae1
#	0x475a44	sync.runtime_SemacquireMutex+0x24						/usr/local/go/src/runtime/sema.go:77
#	0x1a6d77a	sync.(*RWMutex).RLock+0x5a							/usr/local/go/src/sync/rwmutex.go:71
#	0x1a6d756	oxia/server.NewLeaderController.func1+0x36					/src/oxia/server/leader_controller.go:121
#	0xa50f9d	oxia/common/metrics.NewGauge.func1+0x5d						/src/oxia/common/metrics/gauge.go:58
#	0xa2f725	go.opentelemetry.io/otel/sdk/metric.(*meter).RegisterCallback.func1+0x85	/go/pkg/mod/go.opentelemetry.io/otel/sdk/metric@v0.38.0-rc.2.0.20230420231439-002444a2e743/meter.go:263
#	0xa322e6 …
```

Fixed deadlock in leader controller gauge callback

---

server/follower_cursor.go
server/internal_rpc_server.go
server/leader_controller.go
server/leader_controller_test.go
server/public_rpc_server.go
server/quorum_ack_tracker.go
server/quorum_ack_tracker_test.go
server/session.go
server/session_manager.go
server/session_manager_test.go
server/shards_director_test.go
server/standalone.go

During the `BecomeLeader` we need to wait until all the entries in the leader wal are fully replicated. Right now there is no timeout for that operation and the call is stuck waiting even if the gRPC client (oxia coordinator) has given up. 
When the coordinator tries to restart a new term, the process might get deadlock because this node become unresponsive.
```
1 @ 0x4482d6 0x4595de 0x4595b5 0x475a45 0x490785 0x491d76 0x491d55 0x1a722fb 0x1a7b0aa 0x1a6c4b2 0x99841f 0x985a49 0x972163 0x973a2a 0x96c298 0x479ae1
#	0x475a44	sync.runtime_SemacquireMutex+0x24									/usr/local/go/src/runtime/sema.go:77
#	0x490784	sync.(*Mutex).lockSlow+0x164										/usr/local/go/src/sync/mutex.go:171
#	0x491d75	sync.(*Mutex).Lock+0x35											/usr/local/go/src/sync/mutex.go:90
#	0x491d54 …
```

Abort BecomeLeader and Write requests on timeout

---

coordinator/impl/shard_controller.go

When the coordinator sends a `NewTerm` request to the fencing ensemble, it waits for a majority of successful answers. 
After that, we wait for max 100ms and the `NewTerm` is complete. The remaining server will continue to be issued the request in background. 
The problem is that when the answer for original request comes in, after the 100ms threshold, the goroutine is blocked writing on the unbuffered channel, since the original thread already gave up on that request and it's not reading from the channel anymore
```
898 @ 0x4482d6 0x4116ec 0x41129d 0x183197d 0x9daf3b 0x9d43c3 0x9daeb2 0x479ae1
#	0x183197c	oxia/coordinator/impl.(*shardController).newTermQuorum.func1+0x23c	/src/oxia/coordinator/impl/shard_controller.go:443
#	0x9daf3a	oxia/common.DoWithLabels.func1+0x1a …
```

Use buffered channel in coordinator NewTerm quorum response tracking

---

common/ref_count.go
common/ref_count_test.go
server/wal/wal_impl.go
server/wal/wal_ro_segment.go
server/wal/wal_rw_segment.go

Avoid keeping all segments mapped in memory until deleted. Instead keep only few of them at a time.

Close read-only segments after timeout

---

.github/workflows/pr_build_and_test.yaml

CI is failing for a missing package on Ubuntu mirrors.
We should do an `update` before installing.

[build] do apt-get update to avoid missing package versions

---

server/wal/fsync_test.go
server/wal/wal_rw_segment.go

When doing a wal segment rollover, if we allocate and write & sync the entire segment, we are imposing a latency bump while the whole segments is synced to disk. 
Instead we can just seek to the size write 1 byte and we're ready to mmap the whole segment.
Before: 
```
Jul 10 09:02:25.350762 INF Stats - Total ops: 100455.4 ops/s - Failed ops:    0.0 ops/s
Write ops 100455.4 w/s  Latency ms: 50%   6.5 - 95%   8.1 - 99%  93.3 - 99.9%  93.3 - max   93.3
Read  ops    0.0 r/s  Latency ms: 50%   0.0 - 95%   0.0 - 99%   0.0 - 99.9%   0.0 - max    0.0
```
After:
```
Jul 10 09:01:07.853821 INF Stats - Total ops: 109892.6 ops/s - Failed ops:    0.0 ops/s
Write ops 109892.6 w/s  Latency ms: 50%   6.6 - 95%  13.6 - 99%  40.2 - 99.9%  40.2 - max   40.2
Read  ops    0.0 r/s  Latency ms: 50%   0.0 - 95% …
```

Use Seek() to create new wal segment

---

coordinator/impl/node_controller.go

If a storage node restarts and its IP stop responding, the coordinator health check will detect it in a ~2seconds period, though the component that sends the cluster assignements updates will not detect the issue. 
One of the reason is that it's using a grpc stream, so there is no timeout on the send operation (because it would apply to the lifetime of the stream itself, which instead needs to be long-lived). 
The storage servers need to receive the new cluster assignments after restart, otherwise they cannot pass it back to their clients.
To fix the issue, we close the assignments stream whenever the health-check failure is triggered. This will ensure that coordinator will retry after the restart.

Fixed node controller assignemnts update after pods restart

---

docs/getting-started.md

It's easier to copy-paste command lines without the $ sign.

remove $ signs from the command lines in getting-started.md

---

Dockerfile

Fixed security issue in base image
```
┌────────────┬───────────────┬──────────┬────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────┐
│  Library   │ Vulnerability │ Severity │ Status │ Installed Version │ Fixed Version │                         Title                          │
├────────────┼───────────────┼──────────┼────────┼───────────────────┼───────────────┼────────────────────────────────────────────────────────┤
│ libcrypto3 │ CVE-2023-5363 │ HIGH     │ fixed  │ 3.1.3-r0          │ 3.1.4-r0      │ openssl: Incorrect cipher key and IV length processing │
│            │               │          │        │                   │               │ https://avd.aquasec.com/nvd/cve-2023-5363              │
│ …
```

Upgrade OpenSSL in Alpine image

---

.golangci.yaml
cmd/client/cmd.go
cmd/client/cmd_test.go
cmd/client/del/cmd.go
cmd/client/del/cmd_test.go
common/pprof.go
coordinator/impl/cluster_rebalance.go
coordinator/impl/shard_controller.go
oxia/internal/metrics/metrics.go
server/wal/wal_rw_segment.go

chore(*): enable prealloc & predel linters

---

.golangci.yaml
common/logger.go
coordinator/impl/coordinator.go
coordinator/impl/k8s_client_test.go
coordinator/impl/metadata_test.go
server/wal/wal_rw_segment.go

chore(*): enable nilerr, unparam linter

---

oxia/notifications.go
oxia/notifications_test.go

The original for loop never change the initialize `n`, it will cause infinite loop when channel is not empty when close started.

fix(*): avoid infinite loop when notifications close

---

.golangci.yaml
server/wal/treemap.go
server/wal/treemap_test.go
server/wal/wal_ro_segment.go

Add an generic `treeMap` wrapper for `redblacktree` to simplify the wal's code to avoid use of type assert. Currently `gods` didn't have an release of generic support, after the official support of generic is released we should migrate to it.

chore(*): enable revive.typeassert rules

---

server/follower_controller.go
server/follower_controller_test.go

The head snapshot in follower was not updated after loading a snapshot. This can make it look like the follower is not caught up with the leader, when in fact it is.
```
Dec 27 22:43:34.180 |INF| Successfully moved ensemble to a new term component='shard-controller' followers=[{ server-address={ public='oxia-2.oxia-svc.oxia.svc.cluster.local:6648' internal='oxia-2.oxia-sv
c:6649' } entry-id={ term=-1 offset=-1 } },{ server-address={ public='oxia-1.oxia-svc.oxia.svc.cluster.local:6648' internal='oxia-1.oxia-svc:6649' } entry-id={ term=-1 offset=-1 } }] namespace='default' n
ew-leader={ public='oxia-5.oxia-svc.oxia.svc.cluster.local:6648' internal='oxia-5.oxia-svc:6649' } shard=1 term=19
Dec 27 22:43:34.229 |INF| Successfully deleted shard component='shard-controller' namespace='default' …
```

Fixed head offset in follower after a snapshot load

---

oxia/internal/batch/rpc_errors.go
perf/perf.go

The invalid status is going to be transient, so it needs to be retried (within the timeout)

Perform client retry on InvalidStatus error

---

common/client_pool.go
common/logging_client_rpc.go
oxia/async_client_impl.go
oxia/internal/batch/batcher_factory.go
oxia/internal/batch/read_batch.go
oxia/internal/batch/write_batch.go

Ensure shard, namespace and node target address are logged when gRPC calls fail.

Added shard and target node info when logging gRPC failures

---

coordinator/impl/coordinator.go
coordinator/impl/coordinator_e2e_test.go
coordinator/impl/node_controller.go

When we are shrinking the size of a cluster and removing nodes from the coordinator config files, we are stopping the `NodeController` so that we don't react on errors coming from a failed node.
The problem is that some of these nodes might still be online and used by the clients. For example, they might still be marked as "ready" by K8S and still serving the assignments dispatch to clients. 
If the coordinator node controller stops, the node will not receive any update on new leader elections, and if a client is connected to an old (removed) node, it will still operate based on the old leader assignment.
When a node is removed, we leave the NodeController running, though we change the state to `Draining`. When this node stops responding to health-checks, the node controller will then …

Continue to push assignment updates to nodes that were removed from the list

---

server/follower_cursor_test.go

Fixed: https://github.com/streamnative/oxia/issues/327
The assert.Equal may run before `streamEntries` or after `streamEntries`, so the LastPushed maybe -1 or 0.

fix(327): assert the lastPushed as -1 or 0

---

common/logging_client_rpc.go
server/internal_rpc_server.go

After a `NewTerm` operation fails on on a follower, the rpc server is actually returning the wrong error object `err` instead of `err2`. 
This leads to a situation where the coordinator receives a successful response, though the reply is `nil`.
Also, the actual error was not getting printed on the storage node log

Fixed wrong error returned after NewTerm failure

---

server/wal/wal_rw_segment.go
server/wal/wal_test.go

Fixed: https://github.com/streamnative/oxia/issues/426

fix(426): discard entry and writingIdx when TruncateLog

---

Dockerfile

Addressing security issues
```
oxia:latest (alpine 3.18.4)
Total: 4 (UNKNOWN: 0, LOW: 0, MEDIUM: 4, HIGH: 0, CRITICAL: 0)
┌────────────┬───────────────┬──────────┬────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────────────┐
│  Library   │ Vulnerability │ Severity │ Status │ Installed Version │ Fixed Version │                           Title                           │
├────────────┼───────────────┼──────────┼────────┼───────────────────┼───────────────┼───────────────────────────────────────────────────────────┤
│ libcrypto3 │ CVE-2023-6129 │ MEDIUM   │ fixed  │ 3.1.4-r1          │ 3.1.4-r3      │ openssl: POLY1305 MAC implementation corrupts vector      │
│            │               │          │        │                   │               │ …
```

Update Alpine base image to 3.19

---

oxia/async_client_impl.go
oxia/async_client_impl_test.go
oxia/sessions.go
server/kv/notifications_tracker.go
server/session_manager.go
server/session_manager_test.go

Client is not proactively closing the session on client close, to cleanup all the ephemerals. 
Also, we shouldn't be propagating notifications for internal session management keys.

Close session in go client close

---

server/leader_controller.go
server/leader_controller_test.go

Fix handling of GetNotifications() request when leader is not fully initialized

---

coordinator/impl/shard_controller.go

When the leader election on one shard is continuosly failing, this would lead to the node-controller to get stuck as well. 
The reason is that shard-controller mutex is kept busy while retrying the leader election. At the same time, if a node fails, the node controller will try to grab the mutex on the shard as well, leading to a standstill. Technically it's not a deadlock (if the leader election recovers, than node-controller would also recover).
```
1 @ 0x440b0e 0x452018 0x451fef 0x46fc25 0x47ed5d 0x1741f48 0x1741f2a 0x1743328 0x5d4b11 0x5d467c 0x174329b 0x1743234 0xa1c7b3 0xa151fd 0xa1c736 0x473c81
#	0x46fc24	sync.runtime_SemacquireMutex+0x24										/usr/local/go/src/runtime/sema.go:77
#	0x47ed5c	sync.(*Mutex).lockSlow+0x15c											/usr/local/go/src/sync/mutex.go:171
#	0x1741f47 …
```

Use single go-routine instead of mutex for shard-controller

---

coordinator/impl/coordinator_e2e_test.go
coordinator/impl/shard_controller.go

Coordinator is not passing the Term field in the delete shard request, so the server will reject it

Coordinator not passing Term in delete shard request

---

server/follower_controller.go
server/follower_controller_test.go
server/leader_controller.go

If a `DeleteShard` operation fails for invalid term, we must close the controllers, otherwise it will go into a slowly growing resource leak and it will prevent the eventual deletion of the shard, since the DB will always be locked.

Close controller when delete shard fails

---

deploy/charts/oxia-cluster/templates/coordinator-deployment.yaml

For coordinator deployment, it's better to first stop the pod with the old coordinator and then spin up the new pod, avoiding having 2 coordinators running at the same time. 
While there's no correctness issue, we would avoid a brief period or error/retries.

Use `Recreate` rollout strategy for coordinator deployment

---

Dockerfile

Adding `jq` tool since the `oxia client` responses are JSON based, so it makes it easier to visualize them.

Add jq tool to Docker image

---

server/session.go
server/session_manager_test.go

When multiple session are presents on a shards, depending on the key ordering, it was possible that during expiration the index cleanup was also removing index from other session.
That resulted in the ephemeral keys for other session not getting removed when those session expired too.

Fixed session expiry with multiple session in a shard

---

.github/workflows/trivy.yml

The `ALL` passed is not recognized by Trivy

Fixed Trivy scan severity config

---

cmd/coordinator/cmd.go
cmd/coordinator/cmd_test.go
coordinator/coordinator.go
coordinator/impl/coordinator.go
coordinator/impl/coordinator_e2e_test.go
go.mod
maelstrom/main.go
tests/security/tls/tls_encryption_test.go

Fixes https://github.com/streamnative/oxia/issues/461
Not only rely on `clusterConfigRefreshTime`. Support watch conf changes and trigger cluster rebalance.

Watch config changes

---

docs/bare-metal-deploy.md

In the demo of bare mental deploy. we didn't specify the config file type. it might confuse some users and block them adopt oxia.

doc: add file type to avoid confusing

---

server/benchmark_test.go

When I run, `benchmark_test`I found an issue. 
```
ERR Failed to create Oxia client error={"error":"Namespace cannot be empty","kind":"*errors.fundamental","stack":null}
```

*: fix benchmark test issue

---

cmd/server/cmd.go
common/security/tls.go

Follow up the last TLS support PR. This PR is trying to support CLI to set TLS options for Server
- Add new command parameters to set TLS options.
- We might consider using different TLS options for public/internal; we can easily support it in the future if we need it.

tls: support server TLS options

---

cmd/coordinator/cmd.go

Follow up on the last TLS support PR. This PR is trying to support CLI to set TLS options for the Coordinator
- Add new command parameters to set TLS options.

tls: support coordinator TLS options

---

cmd/server/cmd.go
server/server.go
tests/security/tls/tls_encryption_test.go

This PR will support setting different TLS between public and internal for some users who only want to enable TLS for public endpoints. 
- Introduce `internalServerTLS` for the server.
- Adding the test.
This PR is the last TLS support recently, even though we can't expose two ports now(one secure, one insecure). However, We can support it when we really need it.

tls: Support different TLS settings between public and internal

---

oxia/async_client_impl_test.go
oxia/example_test.go
server/kv/db.go
server/kv/db_notifications_test.go
server/kv/db_test.go
server/leader_controller_test.go

Put requests grouped on a single batch will have a unique version-id.
Semantic of version-id is not changed otherwise, different versions of same record will have unique and increasing ids.

Use unique version ids within the same batch

---

server/public_rpc_server.go

Reduce the max size of one individual segment of a list or get response to 2 MB, to have extra room for gRPC headers not to exceed the default 4MB limit of gRPC.

Reduce max segment size in list responses

---

server/leader_controller.go
server/quorum_ack_tracker.go
server/wal/wal_impl.go

Track the quorum offset using a callback. This will free the goroutine handling the write stream for processing the next write batch.

Async tracking of commit offset i QuorumAckTracker

---

coordinator/impl/metadata_configmap.go
coordinator/impl/metadata_file.go
coordinator/impl/metadata_memory.go
coordinator/impl/metadata_test.go

The coordinator will stop all the operations when it stuck in the metadata `bad version` case. this PR is trying to trigger panic when bad version to help auto-restart.  the bad version might caused by many cases:
1. operator/maintainer update the status config.
2. another coordinator updated metadata before shutdown.
> the coordinator is using lock to ensure all the metadata operation is invoke sequentially. which means we don't have race conditions in the process. 
- panic directly when met `BadVersion`
- Update to the latest version when update metadata get `BadVersion`. but we have to change some logics to ensure get version before building the new status to avoid unexpected override.

fix(coordinator): panic when BadVersion in coordinator

---

common/constants.go
maelstrom/replication_rpc_provider.go
server/follower_cursor.go
server/internal_rpc_server.go
server/mock_test.go
server/rpc_provider.go
server/shards_director.go
server/shards_director_test.go
server/standalone.go

During a leader election, an old leader can force back the new leader into a follower mode. 
This does not affect the correctness (eg: the old leader's requests are then ignored because the term is invalid), though it causes the shard to be unavailable until a new leader election is triggered.
The simplified sequence is like:
1. `oxia-1` is the old leader in term: 4
2. Coordinator initiates a new leader election and fences all the nodes
3. `oxia-0` and `oxia-2`  are fenced correctly, while oxia-1 is ignored, and will be retried in background
4. `oxia-2` is elected leader (term: 5)
5. `oxia-1` is still running the leader controller (because it never got successfully fenced), and it keeps trying to replicated to   `oxia-0` and `oxia-2` .
The replicate requests keep failing (because the term …

Add term check on the internal streams, to avoid wrong closures of leader controller

---

cmd/server/cmd.go
cmd/server/cmd_test.go
server/wal/wal_ro_segment.go

the PR #353 remove the default configuration of notification retention. which causes unexpected behaviour when user uses oxia as metadata service. 
especially for distributed lock. the revalidate after session expired will be never triggered.
the current value:
```
{"level":"info","time":"2024-09-18T07:11:48.692719842Z","config":{"PublicServiceAddr":"0.0.0.0:6648","InternalServiceAddr":"0.0.0.0:6649","PeerTLS":null,"ServerTLS":null,"InternalServerTLS":null,"MetricsServiceAddr":"0.0.0.0:8080","AuthOptions":{"ProviderName":"","ProviderParams":""},"DataDir":"/data/db","WalDir":"/data/wal","WalRetentionTime":3600000000000,"WalSyncData":true,"NotificationsRetentionTime":0,"DbBlockCacheMB":4096},"time":"2024-09-18T07:11:48.693399934Z","message":"Starting Oxia server"}
```
- Add …

fix(notification): support notification retention configuration

---

oxia/internal/executor.go
oxia/internal/write_stream.go

Get rid of failed write-streams in Go client SDK. 
This is similar change to https://github.com/streamnative/oxia-java/pull/180 in Java SDK.

[Go client] Recover from write stream failures

---

coordinator/impl/node_controller.go

```
Sep 13 22:30:01.883157 WRN Storage node health check failed error={"error":"node is not actively serving","kind":"*errors.fundamental","stack":null} addr={"internal":"my-server:8190","public":"my-server:9190"} component=node-controller retry-after=1290.424087
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b4f6fa]
goroutine 2364 [running]:
github.com/streamnative/oxia/coordinator/impl.(*nodeController).healthCheckWithRetries.func2({0x35cb5a0, 0xc00020b338}, 0x4cea4f17)
/home/runner/work/oxia/oxia/coordinator/impl/node_controller.go:179 +0x43a
github.com/cenkalti/backoff/v4.doRetryNotify[...](0xc001369ca0, {0x7f82e826bb38, 0xc001100fa0}, 0xc001369d20, {0x0, 0x0}) …
```

Fix NPE in coordinator when closing a half-initialized node controller

---

server/leader_controller.go
server/notifications_dispatcher.go

Fixes #517 #518
Ensure the notification stream go-routine is completely done, before closing the DB

Fixed notification DB read after DB was closed

---

oxia/async_client_impl_test.go
oxia/proto_utils.go

#524 didn't add a session ID when deserialising the version.

fix(tool): follow up #524 to add session id to output

---

cmd/main.go
cmd/wal/cmd.go
cmd/wal/common/option.go
cmd/wal/truncate/cmd.go

Introduce the wal cmd `truncate` command to truncate corrupted unsynced data in the write-ahead log before implementing a CRC-based write-ahead log.

feat(cmd): support wal cmd `truncate` command

---

server/util/crc/crc.go
server/wal/crc_test.go
server/wal/metadata.go
server/wal/wal_impl.go
server/wal/wal_ro_segment.go
server/wal/wal_ro_segment_test.go
server/wal/wal_rw_segment.go
server/wal/wal_rw_segment_test.go

To prevent data corruption from affecting the stability or causing unrecoverable exceptions. Introduce CRC to help validate if the data has corrupted.
- Support chained CRC `CRC(n) = CRC( DATAn, CRCn-1 )` we can validate that followers have exactly the same identical WAL.
- Support `TxnFormatVersion2` for compatibility with the existing format.
- Adding CRC WAL test
will add the proposal later.

feat(wal): support chained CRC for write ahead log

---

coordinator/impl/k8s_client.go
coordinator/impl/metadata_configmap.go

If the status configmap is manually updated with kubectl, the coordinator is not able anymore to update the status.
The error is like: 
```
apply failed with 1 conflict: conflict with "kubectl-edit" using v1: .data.status' 
```
We need to force the coordinator to re-take the ownership of the configmap when trying to make changes.

Force configmap ownership when updating

---

server/wal/wal_impl.go
server/wal/wal_ro_segment_test.go
server/wal/wal_rw_segment.go
server/wal/wal_rw_segment_test.go

Support discarding corrupted uncommitted data to fix Oxia server crash and changing host causes `mmap` didn't persist to the disk properly.
- Adding `commitOffsetProvider` field for WAL.
- Handling corrupted when re-build the index.

feat(wal): support discard corrupted uncommitted data

---

server/kv/db.go

In the old logic, there's the wrong usage for iteration is as follow:
```golang
for it.Next() {
err := updateOperationCallback.OnDelete(batch, it.Key())
if err != nil {
return errors.Wrap(multierr.Combine(err, it.Close()), "oxia db: failed to delete range")
}
}
```
After pr #544, we already added a `deleteRange` callback. Therefore, we can delete this wrong logic directly.

fix(db): delete duplicated callback

---

server/kv/db_test.go

Using in-memory DB will not help validate re-open related logic.
- Using temp dir for re-open related testing.

fix(server): fix wrong options for testing

---

server/follower_controller.go
server/kv/kv_pebble.go
server/kv/notifications_tracker.go
server/leader_controller.go
server/wal/wal_impl.go
server/wal/wal_trimmer.go

```
Oct 16 17:43:07.322395 DBG Received list request component=leader-controller namespace=default request={"endExclusive":"__oxia/session/0000000000000000//","shard":"0","startInclusive":"__oxia/session/0000000000000000/"} shard=2 term=2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1545b3b]
goroutine 1275 [running]:
github.com/streamnative/oxia/server.(*leaderController).list.func1()
/home/runner/work/oxia/oxia/server/leader_controller.go:654 +0x25b
github.com/streamnative/oxia/common.DoWithLabels.func1({0x1b2cf80?, 0xc000833020?})
/home/runner/work/oxia/oxia/common/pprof.go:46 +0x2f
runtime/pprof.Do({0x1b2cd50, 0x332be60}, {{0xc001294c00?, 0x1?, 0x1?}}, 0xc000880d10) …
```

fix(server): fix NPE causes server crash

---

cmd/health/cmd.go
common/client_pool.go
coordinator/impl/mock_test.go
coordinator/impl/node_controller.go
coordinator/impl/rpc_provider.go
maelstrom/coordinator_rpc_client.go

When using Istio between coordinator and storage node, we should discard all the pooled connections in the coordinator, after a node is declared failed (and then it recovers).
The problem is that the gRPC client is not able to detect that TCP has failed, because of the Istio proxy. eg: 
* the istio is still setup to talk with the old pod
* coordinator uses the pooled client and writes to a gRPC stream. There is no failure, even though the channel is not valid
In normal conditions, gRPC will process the TCP failure and open a new connection, though this does not work with Istio in between.
Force to discard all the pooled gRPC clients for target node once we have successfully reconnected with the new pod.

Clear pooled connection after node health checks

---

server/follower_controller.go
server/follower_controller_test.go
server/leader_controller.go

The coordinator will replace the ensemble when swapping the node. Therefore, the old node can't receive new term requests, and the actual shard term will be greater than the old server. and then the old server will keep printing 
```
Invalid term when deleting shard
```
- Allow higher term shard deleting.
- save the deleting term before the new ensemble is elected.

fix(server): allow higher term shard deleting

---

coordinator/impl/cluster_rebalance.go
coordinator/impl/cluster_rebalance_test.go
coordinator/impl/coordinator.go
coordinator/impl/coordinator_e2e_test.go

Currently, we are using the server address as the key to do rebalance. That will be triggered if the user only changes the public address of the server.
We can use the internal address as the unique identification for the user to allow the user to change the public address or other information without the node swapping.
- Introduce `ServerContext` struct as the map value.
- Use the internal address as the filter key.

feat(coordinator): use internal address as unique identification for load balance

---

server/wal/codec/v2.go
server/wal/codec/v2_test.go

The calculation of the actual buf remain size should not include a header.
```
actualBufSize := bufSize - startFileOffset
```

fix(wal): fix wrong overflow validation calculation

---

server/wal/codec/v2.go
server/wal/codec/v2_test.go

We are using `mmap` for WAL, which will reflect a larger buffer than we need. We should skip the index recovery if the current segment is insufficient for a record header.
```
panic: runtime error: slice bounds out of range [:67108867] with capacity 67108864
goroutine 704 [running]:
github.com/streamnative/oxia/server/wal/codec.ReadInt(...)
/src/oxia/server/wal/codec/codec.go:165
github.com/streamnative/oxia/server/wal/codec.(*V2).ReadHeaderWithValidation(0xc001728000?, {0x7fd418691000?, 0x4000000, 0x4000000?}, 0x1a920ac?)
/src/oxia/server/wal/codec/v2.go:109 +0x3ca
github.com/streamnative/oxia/server/wal/codec.(*V2).RecoverIndex(0x34a4da0, {0x7fd418691000, 0x4000000, 0x4000000}, 0x0, 0xff7299, 0xc00087fe40)
/src/oxia/server/wal/codec/v2.go:212 +0x13b …
```

fix(wal): fix recover with insufficient buffer

---

.github/workflows/docker_publish.yaml
server/follower_controller.go
server/follower_controller_test.go

The follower didn't update the `lastAppendedOffset` status when the leader truncated the follower, which caused some expected entries to be filtered by deduplication logic and never recovered.
The server will keep printing:
```
{"level":"warn","time":"2024-11-13T11:38:33.0884113Z","component":"follower-cursor","error":{"error":"rpc error: code = Unknown desc = 20874694 can not immediately follow 20874678: oxia: invalid next offset in wal","kind":"*status.Error","stack":null},"follower":"xxxxxx","namespace":"xxxxxxxx","shard":13,"term":307,"time":"2024-11-13T11:38:33.088438126Z","message":"Error while receiving acks"}
```
- Align `lastAppendedOffset` alone with internal WAL headOffset.

fix(replication): fix wrong memory status block replication

---

common/error_codes.go
coordinator/impl/shard_controller.go
server/follower_controller.go
server/follower_controller_test.go

If the follower has already been fenced and added as a follower to the leader, we can return a specific error to the coordinator when it retries the fencing. 
This will allow the coordinator to recognize that the straggler node is actually already set in the right state, and it will stop the retry process.

Return specific error code on duplicated newTerm

---

server/follower_controller.go

```
WARNING: DATA RACE
Write at 0x00c000676410 by goroutine 408:
github.com/streamnative/oxia/server.(*followerController).setLogger()
/home/runner/work/oxia/oxia/server/follower_controller.go:179 +0x2d2
github.com/streamnative/oxia/server.(*followerController).NewTerm()
/home/runner/work/oxia/oxia/server/follower_controller.go:296 +0x4c4
github.com/streamnative/oxia/server.(*internalRpcServer).NewTerm()
/home/runner/work/oxia/oxia/server/internal_rpc_server.go:125 +0x941
github.com/streamnative/oxia/proto._OxiaCoordination_NewTerm_Handler.func1()
/home/runner/work/oxia/oxia/proto/replication_grpc.pb.go:207 +0xbe
github.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3()
/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/serve …
```

fix(server): fix data race in follower controller

---

server/follower_cursor.go

When the replicate stream fails continuously on a follower, we are retrying every 100ms without exponential backoff.
The reason is that we're resetting the backoff when a new stream is re-established, although the acks on the stream are going to fail again.
Instead of resetting the backoff when the stream is re-established, wait for the first successful ack to come back before resetting.

Reset backoff in replicate stream attempts only after an ack

---

server/follower_controller_test.go

Fix data race in test code: 
```
==================
WARNING: DATA RACE
Write at 0x00c00028aa30 by goroutine 44:
github.com/streamnative/oxia/server.TestFollower()
/home/runner/work/oxia/oxia/server/follower_controller_test.go:136 +0x18bc
testing.tRunner()
/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1690 +0x226
testing.(*T).Run.gowrap1()
/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1743 +0x44
Previous read at 0x00c00028aa30 by goroutine 61:
github.com/streamnative/oxia/server.TestFollower.func1()
/home/runner/work/oxia/oxia/server/follower_controller_test.go:91 +0x86
Goroutine 44 (running) created at:
testing.(*T).Run()
/opt/hostedtoolcache/go/1.23.3/x64/src/testing/testing.go:1743 +0x825
testing.runTests.func1() …
```

Fixed data race in TestFollower

---

coordinator/impl/shard_controller_test.go

Fixes #562
```
--- FAIL: TestShardController_NewTermWithNonRespondingServer (0.10s)
shard_controller_test.go:177: 
Error Trace:	/home/runner/work/oxia/oxia/coordinator/impl/shard_controller_test.go:177
Error:      	Not equal: 
expected: 0x1
actual  : 0x2
Test:       	TestShardController_NewTermWithNonRespondingServer
```

Fixed flaky test TestShardController_NewTermWithNonRespondingServer

---

server/leader_controller.go

This is an alternate approach for #572
The `closeCh` is used to propagate back the error to the client stream handler. Writing on this channel should never block and it's just necessary to write once, all other errors are just ignored.

Fixed deadlock when handling multiple stream entries errors

---

coordinator/impl/shard_controller.go
coordinator/impl/shard_controller_test.go

Follow the [TLA+](https://github.com/streamnative/oxia/blob/6d2bf5de8ffd027804aab6302b80a5118367b061/tlaplus/OxiaReplication.tla#L508). We should choose the highest term entry node as the leader, which can also fix the issue we encountered. 
- The leader can't truncate the following because of the [protection logic](https://github.com/streamnative/oxia/blob/6d2bf5de8ffd027804aab6302b80a5118367b061/server/leader_controller.go#L511-L515). 
```
{"level":"info","time":"2024-11-14T01:04:55.195566194Z","component":"shard-controller","namespace":"xxx","shard":10,"term":278,"time":"2024-11-14T01:04:55.195588258Z","message":"Starting leader election"}
{"level":"info","time":"2024-11-14T01:04:55.218118449Z","component":"shard-controller","entry-id":{"term":"78","offset":"5652112"},"namespace":"xxx", …
```

fix(coordinator): choose highest term and entry node as leader

---

server/leader_controller.go
server/public_rpc_server.go

Return the actual errors if the context is done. 
- Return the actual error to client.
- normal close stream if client closed stream.

feat(server): return actual error when context done

---

go.mod
go.sum

Fix vulnerability: 
```
Package: golang.org/x/net
Installed Version: v0.31.0
Vulnerability CVE-2024-45338
Severity: HIGH
Fixed Version: 0.33.0
Link: [CVE-2024-45338](https://avd.aquasec.com/nvd/cve-2024-45338)
```

Update to x/net 0.33.0

---

.github/workflows/docker_publish.yaml
common/client_pool.go
common/container/container.go

configure default grpc server keepalive enforcement policy
- DefaultGrpcKeepAliveMinTime        = 5 * time.Second
- DefaultGrpcKeepPermitWithoutStream = true
- DefaultGrpcClientKeepAliveTime       = time.Second * 10
- DefaultGrpcClientKeepAliveTimeout    = time.Second * 5
- DefaultGrpcClientPermitWithoutStream = true

feat: configure default grpc server keepalive enforcement policy

---

server/secondary_indexes_test.go

Before fix，when run with `go test -timeout 10m -run ^TestSecondaryIndices_List$ github.com/streamnative/oxia/server -gcflags all='-N' -v -count=10000`, the flaky test reproduced.
After fix, run multi times tests without fail.
fix: https://github.com/streamnative/oxia/issues/582

test(572): fix flaky test with TestSecondaryIndices_List

---

.golangci.yaml
coordinator/impl/shard_controller.go
coordinator/impl/shard_controller_test.go

#579 want to support choosing the highest term as leader. But that PR didn't support it well. 
- Fix the bug might choose a lower term as leader.
- Add enhanced test to cover logic.

fix: leader election should choose highest term

---

Dockerfile

The release published job has failed. FYI: https://github.com/streamnative/oxia/actions/runs/12945972752/job/36110457948
I tried some fixes for the warning log. Then it works.  https://github.com/streamnative/oxia/actions/runs/12946570181

fix: fix docker file error to unblock publish job

---

common/error_codes.go
coordinator/impl/shard_controller.go
server/follower_controller.go
server/follower_controller_test.go

Made newTerm operation idempotent instead of returning AlreadyFenced error

---

common/error_codes.go
coordinator/impl/shard_controller.go
server/leader_controller.go
server/leader_controller_test.go

Align the behaviour as #602. we can also make the `addFollower` idempotent to avoid extra error handling.

feat: make addFollower idempotent to avoid FollowerAlreadyPresent

---

server/internal_rpc_server.go

Add `leaderTerm` for more information when `newTerm` failed.

feat(server): improve the log to help debugging

---

server/session.go
server/session_manager.go

Avoid calling the session "delete" with locks. This will have the potential to cause deadlocks. the following operation will block leaderController `newTerm`.
```
1 @ 0x4773ae 0x452dc5 0x1bb794f 0x1bb08a7 0x1bb0653 0x1bbbbb7 0x1bbbff4 0xad5153 0xac212c 0xad50cd 0x47f661
#	0x1bb794e	github.com/streamnative/oxia/server.(*quorumAckTracker).WaitForCommitOffset+0x10e	/src/oxia/server/quorum_ack_tracker.go:181
#	0x1bb08a6	github.com/streamnative/oxia/server.(*leaderController).write+0x1e6			/src/oxia/server/leader_controller.go:799
#	0x1bb0652	github.com/streamnative/oxia/server.(*leaderController).Write+0x32			/src/oxia/server/leader_controller.go:782
#	0x1bbbbb6	github.com/streamnative/oxia/server.(*session).delete+0x7f6				/src/oxia/server/session.go:131
#	0x1bbbff3 …
```

fix(server): fix deadlock caused by session close/delete

---

common/callback/callback.go
common/callback/once.go
common/callback/once_test.go
common/error_codes.go
server/internal_rpc_server.go
server/leader_controller.go
server/quorum_ack_tracker.go
server/quorum_ack_tracker_test.go

This is the follow-up PR for #607. We should fail the pending request when `quorumAckTracker` closes.
- Introduce a callback
- fail pending request when `quorumAckTracker` closes.

fix(server): fail pending request when `quorumAckTracker` closed

---

common/error_codes.go
oxia/sessions.go
server/public_rpc_server.go
server/session_manager.go

Fix：https://github.com/streamnative/oxia/issues/506

test(506): regarded as a successful closure  when session not found

---

server/leader_controller.go

The status already became `LEADER` if `addFollower` failed. that will make public server accept requests.
```
{"level":"debug","time":"2025-02-25T03:15:00.886431474Z","component":"db","key":"2f52b44b5408436894ff635087ff0f37-000000000000000013
97-00000000000000002794-00000000000000004191","namespace":"default","shard":11,"version":{"version_id":2932110,"created_timestamp":1
740453300879,"modified_timestamp":1740453300879},"time":"2025-02-25T03:15:00.886435947Z","message":"Applied put operation"}
{"level":"debug","time":"2025-02-25T03:15:00.886448265Z","component":"db","key":"__oxia/commit-offset","namespace":"default","shard"
:11,"version":{"version_id":-1,"modifications_count":2577974,"created_timestamp":1740396891493,"modified_timestamp":1740453300879}," …
```

fix: data lost when BecomeLeader failed

---

server/wal/wal_impl.go
server/wal/wal_trimmer_test.go

Fix: https://github.com/streamnative/oxia/issues/580
we must close trimmer without lock, because when it running doTrim, will acquire lock and cause an deadlock.
```
panic: test timed out after 10m0s
running tests:
TestWalTrimUpToCommitOffset (7m11s)
TestWalTrimUpToCommitOffset/test-69 (7m8s)
goroutine 21768 [running]:
testing.(*M).startAlarm.func1()
/Users/bytedance/.gvm/gos/go1.23.5/src/testing/testing.go:2373 +0x718
created by time.goFunc
/Users/bytedance/.gvm/gos/go1.23.5/src/time/sleep.go:215 +0x44
goroutine 1 [chan receive, 7 minutes]:
testing.(*T).Run(0x140001bb860, {0x1056e4c3a, 0x1b}, 0x1059d80e0)
/Users/bytedance/.gvm/gos/go1.23.5/src/testing/testing.go:1751 +0x7e4
testing.runTests.func1(0x140001bb6c0)
/Users/bytedance/.gvm/gos/go1.23.5/src/testing/testing.go:2168 +0x98 …
```

fix(580): close trimmer without lock to avoid deadlock

---

oxia/async_client_impl.go
oxia/async_client_impl_test.go
oxia/internal/batch/read_batch_test.go
oxia/internal/model/model.go
oxia/options_get.go

Support `IncludeValue` to get the operation to have the ability to peek at the first or last key without extra cost.

feat: support `IncludeValue` for get operation

---

server/wal/readwrite_segment.go
server/wal/wal_test.go

Fix: https://github.com/streamnative/oxia/issues/635

fix(635): validate offset in bound when read entry in segment

---

cmd/coordinator/cmd_test.go
coordinator/impl/cluster_rebalance.go
coordinator/impl/cluster_rebalance_test.go
coordinator/impl/cluster_updates.go
coordinator/impl/cluster_updates_test.go
coordinator/impl/coordinator.go
coordinator/impl/coordinator_e2e_test.go
coordinator/impl/mock_test.go
coordinator/impl/node_controller.go
coordinator/impl/node_controller_test.go
coordinator/impl/rpc_provider.go
coordinator/impl/shard_controller.go
coordinator/impl/shard_controller_test.go
coordinator/model/cluster_common.go
coordinator/model/cluster_config.go
coordinator/model/cluster_config_test.go
coordinator/model/cluster_status.go
coordinator/model/cluster_status_test.go
maelstrom/coordinator_rpc_client.go
maelstrom/main.go
tests/security/auth/auth_oidc_test.go
tests/security/tls/tls_encryption_test.go

Introduce server identifiers to support unique names that do not bind to internal or public addresses. 
- rename `ServerAddress` => `Server`
- use `GetIdentifier` method instead of using `Internal` address directly.
- use the internal address as an identifier by default for backwards compatibility, and I will introduce the special `Equals` method for migration from internal address to name as an identifier in the next PR.

feat: introduce server identifier

---

.github/workflows/pr_build_and_test.yaml

support tmate to debug some CI failures that do not provide useful information.  for example: `CatChen/check-git-status-action@v1`

feat: support tmate to debug ci failure

---

server/follower_controller_test.go

We can disable the debug log to reduce the CI pressure. and then we can enable it when we debug the issue. 
- disblae debug level on testing.

feat: disable debug log for testing

---

server/kv/db.go

We haven't updated the version for internal keys. therefore, we can also avoid extra version check cost for internal keys. especially for `commit-offset` and `last-version-id` keys.
- only check versions if the key is not internal.

feat: avoid extra version check cost for internal keys

---

server/leader_controller.go
server/leader_controller_test.go
server/public_rpc_server.go
server/secondary_indexes_test.go

This reverts commit 1600877bb0d0c90bed8fb33dcd9a1e2d3f2866fd.
This PR is reverting to PR #651, which introduces another deadlock. I will push another PR to simply fix the no-response issue first, then consider the code refactor. :/ 
```
11 @ 0x4773ae 0x40b30d 0x40af77 0x1bb4845 0x1bbac43 0x9e2527 0x9c47d2 0x9b2d47 0x9b495a 0x9ad6ff 0x47f661
#	0x1bb4844	github.com/streamnative/oxia/server.(*leaderController).RangeScan+0x224					/src/oxia/server/leader_controller.go:712
#	0x1bbac42	github.com/streamnative/oxia/server.(*publicRpcServer).RangeScan+0x202					/src/oxia/server/public_rpc_server.go:269
#	0x9e2526	github.com/streamnative/oxia/proto._OxiaClient_RangeScan_Handler+0x106					/src/oxia/proto/client_grpc.pb.go:528
#	0x9c47d1	github.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetri …
```

Revert "fix: no response when range scan return err (#651)"

---

server/public_rpc_server.go

follow up #651 #652. this is the simplest fix for no-response issue. 
- return missing error directly.

fix: follow up #652 to return error directly

---

server/leader_controller.go

Add missing return error to avoid potential no response.
- return error when read.
- ensure we will close the channel.

fix: add missing error return

---

server/public_rpc_server.go

A client that does not include a shard id with a read request will crash the server.
- return codes.InvalidArgument if a ReadRequest does not include shard id
*Note*: despite the comment in client.proto, the Shard field is not actually optional. This commit does not change the protobuf definition as the comment suggests this is subject to change.
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102208274]
goroutine 102 [running]:
github.com/streamnative/oxia/server.(*publicRpcServer).Read(0x140001e51c0, 0x140002e83c0, {0x102c0f5b0, 0x14000694380})
/Users/pixi/src/streamnative/oxia/server/public_rpc_server.go:167 +0x124
github.com/streamnative/oxia/proto._OxiaClient_Read_Handler({0x102ac1380, …
```

fix: don't crash if client does not send shard id

---

coordinator/impl/node_controller.go
server/assignment_dispatcher.go
server/assignment_dispatcher_test.go

Adding assignments updates log on both the coordinator and server-side because it's a critical path.
- Adding info logs on the assignment of the shares dispatching path.

feat: support shares assignments logs

---

.github/workflows/trivy.yml
server/kv/db.go
server/kv/db_test.go

Move version ID generation behind the callback validation to avoid any potential inconsistency by abnormal conditions.
- Move version ID generation behind the callback handling

fix: move the version id generation behind error handling

---

docs/go-api.md

Reflect the changes of #474 in the Go client API examples.

docs: update go client api examples

---

coordinator/selectors/ensemble/selector_test.go

https://github.com/streamnative/oxia/actions/runs/14671629274/job/41179262167
Fix the flaky test, because the ensemble selector might choose s2 as an ensemble. We just need to ensure "s1" and "s2" are isolated. 
- Change the assertion to `assert.True(t, slices.Contains(esm, "s1") || slices.Contains(esm, "s2"))`

fix(coordinator): fix the flaky TestSelectMultipleAntiAffinitiesSatisfied

---

server/leader_controller.go
server/leader_controller_test.go
server/public_rpc_server.go
server/session_manager_test.go

This PR is a follow-up to #662 to align the streaming callback for the Read endpoint. 
- Use `StreamingCallback` for Read operation.

feat: followup #662 to use stream callback for Read

---

coordinator/impl/coordinator.go
coordinator/impl/coordinator_test.go

Fixes #695 and addresses some potential inconsistencies in metadata updating.
Update the coordinator's memory status when initialising the election.

fix(coordinator): Update memory status when initializing election

---

.github/workflows/pr_build_and_test.yaml

Potential fix for [https://github.com/streamnative/oxia/security/code-scanning/14](https://github.com/streamnative/oxia/security/code-scanning/14)
To fix the issue, we will add a `permissions` block to the `maelstrom` job to explicitly define the minimal permissions required. Based on the job's operations, it appears to need:
- `contents: read` to access the repository's contents.
- `actions: write` to upload artifacts using the `actions/upload-artifact` action.
This change will ensure the job adheres to the principle of least privilege while maintaining its functionality.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 14: Workflow does not contain permissions

---

.github/workflows/pr_build_and_test.yaml

Potential fix for [https://github.com/streamnative/oxia/security/code-scanning/13](https://github.com/streamnative/oxia/security/code-scanning/13)
To fix the issue, we will add a `permissions` block to the `chaos-mesh` job. Based on the workflow's steps, it primarily interacts with the repository's contents (e.g., checking out the code) and uses external tools like Docker, Helm, and Kubernetes. Therefore, the minimal required permission is `contents: read`. This ensures that the job has only the necessary permissions to perform its tasks.
The `permissions` block will be added under the `chaos-mesh` job definition, specifying `contents: read`.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 13: Workflow does not contain permissions

---

.github/workflows/pr_build_and_test.yaml

Potential fix for [https://github.com/streamnative/oxia/security/code-scanning/12](https://github.com/streamnative/oxia/security/code-scanning/12)
To fix the issue, we will add an explicit `permissions` block to the `build` job. Based on the steps in the `build` job, it only requires `contents: read` permissions to check out the repository and perform the build and test steps. This change will ensure that the job does not have unnecessary write permissions.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 12: Workflow does not contain permissions

---

common/channel/noblock.go
server/public_rpc_server.go
server/public_rpc_server_test.go

commit 93101002e1e1888eb4181b6ffb19b3a27e52016e
Author: mauricebarnum <maurice.barnum@gmail.com>
Date:   Tue Jun 10 19:33:06 2025 -0700
public_rpc_server_test: test handling of a client closing a WriteStream
After a client sends a write request, receives a response, and closes
the write end of the stream, reading from the stream should yield an EOF
commit 4a56ff8d237b8e04f47a9425c065fbadc49413d8
Author: mauricebarnum <maurice.barnum@gmail.com>
Date:   Tue Jun 10 19:37:13 2025 -0700
Fix WriteStream regression: don't send an error client close
The refactoring in c90c79172d6cda7ae9ff199a8a9bf8a275fd5d61 makes
a change that sends an unknown error message to the client when it
encounters either a read EOF or an internal context is closed.  This
can confuse a client that doesn't expect to see …

Fix WriteStream regression: don't send an error client close

---

common/rpc/closable_health_server.go
common/rpc/closeable_health_server.go
server/assignment_dispatcher.go
server/assignment_dispatcher_test.go
server/internal_rpc_server.go
server/internal_rpc_server_test.go
server/server.go
server/server_test.go

Supports closable health servers to avoid the GRPC server graceful shutdown getting stuck due to the client watch stream not being closed.
- Introduce a component named `ClosableHeathServer`
- Close the `ClosableHeathServer` when the server closes.
- Add a test for that.

fixes: support closable health server to avoid being stuck

---

server/kv/db.go
server/kv/db_test.go

introduce committed version IDs to avoid accidentally writing dirty version ID trackers
- Introduce the committed version ID to avoid increasing the version if the whole write logic failed.
- Add another condition on TestDBVersionIDWithError to reproduce the issue.

feat: introduce committed version IDs to avoid accidentally writing dirty version ID trackers

---

server/kv/db.go
server/secondary_indexes.go

fixes the potential pooled object leak and NPE.
- Fixes the potential pooled object leak.
- Avoid the potential nil object causes `se.ReturnToVTPool()` panic.

fix(obj): fix the potential pooled object leak

---

server/public_rpc_server.go

fixes: https://github.com/oxia-db/oxia/issues/745
The current logic will return `nil,nil` to the client when the session is not found. which is confusing the client side because we didn't give the correct response body, but an OK status.

fix(session): avoid complete rpc without response

---

server/kv/kv_pebble.go

It's safer to use the specific version for broader compatibility with downgrades

Pin Pebble disk format to a specific version
